### PR TITLE
Fixes issues on AIX platform where 'root' isn't group.

### PR DESCRIPTION
**Pull request by johnbellone**
This should use default group which is root and default gid for root.

### CODE REVIEW

**Comment by coderanger** [comment]
Does the wheel group still have gid 0? Usual fix for this when working on non-Linux is:

``` ruby
user 'root'
group 0
```

**Comment by johnbellone** [comment]
I'll need to check, but doesn't the resources default to root and group on platform? What would this be on Windows?

**Comment by coderanger** [comment]
If you don't specify it defaults to whatever Chef happens to be running as, which could be any user in theory.

**Comment by johnbellone** [comment]
The default group in question here isn't wheel, but a `group 0` would effectively give the same deal. The vast majority of users are running Chef as root. This patch doesn't make it explicit, but I think it is the safest way to make it portable amongst the platforms.

**Pull request closed without merging**
